namespace RPGMinesweeper
{
    public enum MonsterType
    {
        None,
        Rat,
        RatKing,
        MimicChest,
        Minotaur,
        Wizard,
        Demon,
        Devil,
        Imp,
        Beholder,
        Bat,
        Spider,
        Slime,
        Ghost,
        Skeleton,
        Dragon, 
        WaterElement,
        FireElement,
        EarthElement,
        AirElement,
        Gargoyle,
        Troll,
        Ogre,
        DemonLord,
        Zombie, 
        Banshee,
        Lich,
        Witch,
        Werewolf,
        Mummy,
        Medusa,
        Cyclops,
        
    }
} 